name: Test

on: [push]

jobs:
  test:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.18

      - name: Run tests
        run: |
          go test -v ./...

